### ISSUE TITLE
Call me confused...can't get live-reload to work

### ISSUE THREAD

**Issue by Merovex** [sean-perkins/angular-electron-seed#12]
I'm trying to get live-reload to work so that I can make changes to Angular files and have Electron automatically reload.

In one window I have running `npm run start.watch`. Whenever I change a file, it goes through the process of rebuilding. However, electron does not reload. I hit CMD+R to reload, and I'm greeted with a white screen. 

Please explain to me where I'm failing to implement this right. The documentation is a bit spartan.

**Comment by sean-perkins** [comment]
Did you run this in conjunction with: `npm run watch`? One task spins up the Angular/Electron build and tries to bind to an open port and the other, opens a port for the live-reload communication. 

I agree it's not very clear cut. Would love contributions on that part. Especially since I'm a little overbooked with work for the next month.

**Comment by Merovex** [comment]
Dude, this is cool. Thank you for the prompt reply. I was either running the wrong commands, or in the wrong order. I got it to work running in the following order:

1. npm run start.watch
2. npm run watch
