### ISSUE TITLE
MacOS - Error on startup - Error: connect ECONNREFUSED 127.0.0.1:30080

### ISSUE THREAD

**Issue by DiegoNovati** [sean-perkins/angular-electron-seed#8]
Hi,
I've clone your project, I've executed "npm i" and then "npm run start" but Electron displays the following error message:

A JavaScript error occurred in the main process 
Uncaught Exception:
Error: connect ECONNREFUSED 127.0.0.1:30080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

Obviously it's trying to call the local Angular App running on port 30080, but I don't know how to start it. Could you please provide this information ?
Another question: how do you suggest to proceed during the development of the Angular components and see the changes in real time inside Elecrton ? Could you provide more information about this ?
Thank you very much, your project is really useful !

Diego

**Comment by FantasticFiasco** [comment]
Same on Windows

**Comment by sean-perkins** [comment]
Please refer to the already closed issue discussing this: https://github.com/sean-perkins/angular-electron-seed/issues/6. 

The angular app is not running on 30080. That's the socket communication between electron and angular, to handle live-reload. Since electron isn't running at the time that it initially bootstraps, it throws an error. Running both at the same time resolves the issue.

**Comment by FantasticFiasco** [comment]
Thanks!
